### ISSUE TITLE
Error: Evaluation failed: DOMException: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules     at _ (__puppeteer_evaluation_script__:4:20)

### ISSUE THREAD

**Issue by pat-s** [astefanutti/decktape#157]
On some local html I get the following error with v2.8.5 while v2.8.0 works: 

```
Error: Evaluation failed: DOMException: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules
    at _ (__puppeteer_evaluation_script__:4:20)
```

I cannot reproduce this locally with an example presentation. Using their online version works. 

I used the `docker` approach.

**Comment by pat-s** [comment]
[reprex.zip](https://github.com/astefanutti/decktape/files/2246046/reprex.zip)

If I call the docker approach on slides that are hosted online, both 2.8.0 AND 2.8.5 are working

```
docker run --rm -t -v `pwd`:/slides -v $HOME:$HOME astefanutti/decktape:2.8.5 https://pjs-web.de/files/basis_descriptive.html ~/Downloads/test.pdf

Loading page https://pjs-web.de/files/basis_descriptive.html ...
Failed to load resource: the server responded with a status of 404 ()
Failed to load resource: the server responded with a status of 404 ()
Loading page finished with status: 200
Remark JS plugin activated
Printing slide #2       (2/2) ...
Printed 2 slides
```

If I execute the same statement on a local file, I get:

```
docker run --rm -t -v `pwd`:/slides -v $HOME:$HOME astefanutti/decktape:2.8.5 ~/Downloads/basis_descriptive.html ~/Downloads/test.pdf

Loading page file:///home/pjs/Downloads/basis_descriptive.html ...

Unable to load resource from URL: file:///home/_setup/css/xaringan-theme.css
Failed to load resource: net::ERR_FILE_NOT_FOUND
Unable to load resource from URL: file:///home/_setup/css/tweaks.css
Failed to load resource: net::ERR_FILE_NOT_FOUND
Loading page finished with status: 0
Remark JS plugin activated

Error: Evaluation failed: DOMException: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules
    at _ (__puppeteer_evaluation_script__:4:20)
```

Ignore the warnings about the missing CSS files there. But its interesting that both versions react in a different way to the missing CSS files (not shown here).

**Comment by astefanutti** [comment]
It should be fixed with 272b70249253946c85479a71575e41eb75b474f4 that ships with 2.8.6 release.

**Comment by siddhantgoel** [comment]
I'm running into the same issue when trying to export a remarkjs presentation.

I've tried adding the `--allow-file-access-from-files` arg as mentioned in the [errors section in the README](https://github.com/astefanutti/decktape#errors) but the error still persists.

I'm using decktape version 2.8.9, and Chromium 70.0.3538.67 (Arch Linux).

**Comment by astefanutti** [comment]
The `--chrome-arg` option, as documented in the README, has been introduced in Decktape version 2.9.0. That being said, the `--allow-file-access-from-files` option flag was set by default in version 2.8.9. 

It's not clear why that would fail even with the `--allow-file-access-from-files` option flag. As any Chrome option can be passed with the `--chrome-arg` option in version 2.9.0, you could upgrade your version of Decktape and try with the `--disable-web-security` option flag.

**Comment by siddhantgoel** [comment]
My bad, I saw the 2.8.9 npm badge and thought the documentation is for that version.

How can I install 2.9.0? `yarn add 2.9.0` does not show 2.9.0 in the list of available versions. Thanks for your help!

**Comment by siddhantgoel** [comment]
No worries, 2.9.0 seems to work! :tada:

**Comment by pat-s** [comment]
> How can I install 2.9.0? 

There is also an AUR package `nodejs-decktape` :)

**Comment by siddhantgoel** [comment]
There's always an AUR package. :)

**Comment by ahmadawais** [comment]
It's again not working in the v2.9.2 :(

**Comment by astefanutti** [comment]
@ahmadawais have you tried with the `--chrome-arg=--allow-file-access-from-files` option flag, or `--chrome-arg=--disable-web-security`?

**Comment by ahmadawais** [comment]
I ran with `decktape remark https://wordsesh2019.ahmadawais.com/ slide.pdf --chrome-arg=--disable-web-security`

And that worked. Mention this in the readme as well. `--chrome-arg=--allow-file-access-from-files` didn't work.
